# Generated by Django 3.2.4 on 2021-09-30 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210930_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='adrress2',
            new_name='address2',
        ),
    ]
